### ISSUE TITLE
Split skos.shacl.ttl

### ISSUE THREAD

**Issue by nichtich** [skohub-io/shapes#6]
The shapes file should better be split into e.g.

- [x] core SKOS integrity rules (see #3)
- [ ] SKOS-XL rules
- [ ] best practice (warning severity)
- [ ] analysis rules (information severity)
- [ ] additional rules from Skohub
- [ ] additional rules from coli-conc/JSKOS
- [ ] [XKOS](http://linked-statistics.github.io/xkos/xkos-best-practices.html) rules

**Comment by sroertgen** [comment]
Indeed.
I'm currently working on adding all the valid and invalid examples from the [SKOS Reference](https://www.w3.org/TR/skos-reference) and adjusting the shape respectivley in branch https://github.com/skohub-io/shapes/tree/constraint-property-groups.

So that would result in 
- [x] core SKOS integrity rules (see https://github.com/skohub-io/shapes/issues/3)

After that we can proceed on the other shapes.

**Comment by sroertgen** [comment]
@nichtich I found this document from qSKOS regarding quality issues: https://github.com/cmader/qSKOS/wiki/Quality-Issues#Ambiguous_Notation_References

Are you aware of any other best practice recommendation regarding SKOS?

Otherwise I would maybe go with this for implementing a best-practice shape

CC @acka47 @osma @wetneb

**Comment by sroertgen** [comment]
@nichtich And what do you mean with "analysis rules"?

**Comment by nichtich** [comment]
This issue can better closed in favour of invidual issues for SKOS core rules, [qSKOS](https://github.com/cmader/qSKOS/wiki/Quality-Issues) rules, etc.

**Comment by sroertgen** [comment]
good point. Closing this in favour of #9 

Anyone wanting to discuss other rules and shapes, feel free to open an issue.
